-- ============================================================
-- PADELORGANIZERS.COM — Fase 6 directorio: Zaragoza
-- 10 clubes/escuelas reales de Zaragoza (privados + padel municipal
-- Zaragoza Pádel Club en CDMs Delicias y Almozara), geocodificados
-- con Photon/OSM.
-- Idempotente: reejecutable sin duplicar (ON CONFLICT slug).
-- ============================================================

insert into public.clubes
  (name, slug, city, province, address, latitude, longitude, geo_approx,
   phone, email, website, courts, indoor, grass, booking_platform,
   has_school, has_shop, is_verified, status, description)
values
  ('Pádel Zaragoza', 'padel-zaragoza', 'Zaragoza', 'Zaragoza',
   'C/ San Juan Bautista de la Salle, 1, 50012 Zaragoza', 41.6334286, -0.92736, false,
   '+34 876 77 66 22', 'info@padelzaragoza.es', 'https://padelzaragoza.es/',
   '14 pistas (outdoor e indoor)', true, 'sintético', 'Web Propia / Teléfono', true, true,
   false, 'pendiente_verificacion',
   'El mayor club de pádel de Zaragoza y Aragón: 14 pistas, la mayor escuela de Aragón, torneos, eventos corporativos y gastrobar.'),
  ('Pádel Indoor Aragón', 'padel-indoor-aragon', 'Zaragoza', 'Zaragoza',
   'Camino de la Raya, s/n, 50002 Zaragoza', 41.6438521, -0.8557242, false,
   '', '', 'https://padelindooraragon.com/',
   '6 pistas cubiertas', true, 'sintético', 'Web Propia / Teléfono', true, false,
   false, 'pendiente_verificacion',
   'Club indoor con 6 pistas cubiertas, escuela de pádel y zona de ocio y restauración con terraza ajardinada.'),
  ('CD Montecanal', 'cd-montecanal', 'Zaragoza', 'Zaragoza',
   'C/ de la Mesta, 35 (s/n), 50012 Zaragoza', 41.6296663, -0.944131, false,
   '+34 976 75 58 00', 'padel@cdmontecanal.com', 'https://cdmontecanal.com/padel/',
   '10 pistas (6 indoor, 4 outdoor)', true, 'sintético', 'Web Propia / Teléfono', true, false,
   false, 'pendiente_verificacion',
   'Montecanal Centro Deportivo: 6 pistas de pádel de cristal indoor y 4 exteriores, con escuela, torneos y campus.'),
  ('Regal Pádel Club', 'regal-padel-club', 'Zaragoza', 'Zaragoza',
   'CC Alcampo Los Enlaces, Antigua Carretera N-II, KM 315,2, Local 31, 50012 Zaragoza', 41.6448803, -0.923477, true,
   '', '', 'https://regalpadelclub.com/',
   '8 pistas indoor', true, 'sintético', 'Web Propia / Reserva Online', true, false,
   false, 'pendiente_verificacion',
   'Club indoor de referencia con 8 pistas, restaurante y zona salud, en el CC Alcampo Los Enlaces.'),
  ('Pádel Plaza', 'padel-plaza', 'Zaragoza', 'Zaragoza',
   'Av. Diagonal Plaza, 3, Nave C, 50197 Zaragoza', 41.6347101, -0.9921257, false,
   '', '', 'https://www.padelplaza.es/',
   'Pistas indoor y outdoor', true, 'sintético', 'Web Propia (Reserva Online)', true, false,
   false, 'pendiente_verificacion',
   'Club de pádel en el complejo Diagonal Plaza con reserva online de pistas y escuela.'),
  ('Zaragoza Pádel Club', 'zaragoza-padel-club', 'Zaragoza', 'Zaragoza',
   'C/ Madre Genoveva Torres Morales, 5, Local 17, 50006 Zaragoza', 41.6417144, -0.8894862, false,
   '+34 976 79 55 33', 'info@zaragozapadelclub.es', 'https://www.zaragozapadelclub.es/',
   '38 pistas (19 cubiertas) en 10 CDMs municipales', true, 'sintético', 'Web Propia / Teléfono', true, false,
   false, 'pendiente_verificacion',
   'Gestora del pádel municipal de Zaragoza: 38 pistas (19 cubiertas) repartidas en 10 Centros Deportivos Municipales.'),
  ('C.N. Helios', 'cn-helios', 'Zaragoza', 'Zaragoza',
   'Parque Macanaz, s/n, 50018 Zaragoza', 41.6589887, -0.879579, false,
   '+34 976 520 255', 'cnhelios@cnhelios.com', 'https://www.cnhelios.com/instalaciones/pistas-de-padel',
   '5 pistas de pádel + tenis, squash y gimnasio', false, 'sintético', 'Web Propia / Teléfono', true, false,
   false, 'pendiente_verificacion',
   'Histórico club social de Zaragoza: 5 pistas de pádel, tenis, squash, gimnasio y piscinas junto al Parque Macanaz.'),
  ('CDM Delicias (Zaragoza Pádel Club)', 'cdm-delicias', 'Zaragoza', 'Zaragoza',
   'C/ Moreno Alcañiz, 2, 50017 Zaragoza', 41.655598, -0.9180261, false,
   '+34 976 72 61 31', 'cdmdelicias@zaragoza.es', 'https://www.zaragozapadelclub.es/',
   '6 pistas (4 cubiertas)', true, 'sintético', 'Web Propia / Teléfono', false, false,
   false, 'pendiente_verificacion',
   'Centro Deportivo Municipal Delicias-Bombarda: 6 pistas de césped artificial (4 cubiertas), gestionado por Zaragoza Pádel Club.'),
  ('CDM Almozara (Zaragoza Pádel Club)', 'cdm-almozara', 'Zaragoza', 'Zaragoza',
   'Av. de la Almozara, 65, 50001 Zaragoza', 41.66349, -0.8995166, false,
   '+34 976 72 64 01', 'cdmalmozara@zaragoza.es', 'https://www.zaragozapadelclub.es/',
   '4 pistas cubiertas', true, 'sintético', 'Web Propia / Teléfono', false, false,
   false, 'pendiente_verificacion',
   'Centro Deportivo Municipal La Almozara: 4 pistas de pádel cubiertas gestionadas por Zaragoza Pádel Club.'),
  ('Real Zaragoza Club de Tenis', 'rzct', 'Zaragoza', 'Zaragoza',
   'Carretera Aeropuerto, KM 5,8, 50190 Zaragoza', 41.6646515, -0.9994234, false,
   '+34 976 346 193', 'administracion@rzct.com', 'https://www.rzct.com/',
   '9 pistas de pádel + 19 de tenis', false, 'césped sintético', 'Playtomic', true, false,
   false, 'pendiente_verificacion',
   'Club histórico (1907) con 9 pistas de pádel y 19 de tenis (13 de tierra batida), gimnasio, piscina y zonas verdes.');