-- ============================================================
-- PADELORGANIZERS.COM — Fase 7 directorio: Bilbao y entorno
-- 10 clubes reales de Bilbao (privados + Bilbao Kirolak municipal)
-- y área metropolitana (Zamudio, Derio, Barakaldo),
-- geocodificados con Photon/OSM.
-- Idempotente: reejecutable sin duplicar (ON CONFLICT slug).
-- ============================================================

insert into public.clubes
  (name, slug, city, province, address, latitude, longitude, geo_approx,
   phone, email, website, courts, indoor, grass, booking_platform,
   has_school, has_shop, is_verified, status, description)
values
  ('Bilbao Padel Indoor', 'bilbao-padel-indoor', 'Zamudio', 'Bizkaia',
   'Polígono Torrelarragoiti, 7A, 48170 Zamudio', 43.2763309, -2.851492, false,
   '+34 675 20 85 33', 'info@bilbaopadelindoor.com', 'https://bilbaopadel.com/',
   '5 pistas indoor', true, 'sintético', 'Playtomic', true, false,
   false, 'pendiente_verificacion',
   'Bilbao (Zamudio): 5 pistas indoor con cafetería en el Pol. Torrelarragoiti.'),
  ('Padel Bizkaia', 'padel-bizkaia', 'Zamudio', 'Bizkaia',
   'Polígono Torrelarragoiti, 6B, 48170 Zamudio', 43.2763309, -2.851492, false,
   '+34 944 52 00 00', '', 'https://padelbizkaia.com/',
   '10 pistas panorámicas', true, 'panorámico', 'Web Propia / Playtomic', true, false,
   false, 'pendiente_verificacion',
   'Bilbao (Zamudio): 10 pistas panorámicas en el Pol. Torrelarragoiti.'),
  ('Pádel Derio Club', 'padel-derio-club', 'Derio', 'Bizkaia',
   'Larrauri Kalea, 1, 48160 Elexalde Derio', 43.2929493, -2.8782174, false,
   '', '', 'https://www.padelderio.com/',
   'Pistas indoor y outdoor', true, 'sintético', 'Playtomic', true, false,
   false, 'pendiente_verificacion',
   'Derio: club de pádel en el Pol. Larrauri, junto a Bilbao.'),
  ('PADELBAI', 'padelbai', 'Derio', 'Bizkaia',
   'Avenida Santo Domingo, 10, 48160 Derio', 43.2888868, -2.8901819, false,
   '', '', 'https://www.padelbai.com/',
   'Pistas indoor', true, 'sintético', 'Playtomic', true, false,
   false, 'pendiente_verificacion',
   'Derio: centro de pádel indoor en la Av. Santo Domingo.'),
  ('Padel Indoor Center', 'padel-indoor-center', 'Barakaldo', 'Bizkaia',
   'Calle Kareaga, 115, 48903 Barakaldo', 43.2888222, -3.0131626, false,
   '+34 944 371 750', '', 'https://padelindoorcenter.com/',
   'Pistas indoor', true, 'sintético', 'Playtomic', true, false,
   false, 'pendiente_verificacion',
   'Barakaldo: centro indoor en el Pol. de La Llana, a 5 minutos de Bilbao.'),
  ('Club Deportivo Bilbao', 'club-deportivo-bilbao', 'Bilbao', 'Bizkaia',
   'Alameda Recalde, 28, 48009 Bilbao', 43.2672772, -2.9331599, false,
   '+34 944 241 522', 'cdb@clubdeportivobilbao.com', 'https://www.clubdeportivobilbao.com/',
   'Pistas de pádel cubiertas', true, 'sintético', 'Web Socios / Teléfono', false, false,
   false, 'pendiente_verificacion',
   'Bilbao: histórico club social con pistas de pádel cubiertas en el centro.'),
  ('Polideportivo San Inazio (Bilbao Kirolak)', 'polideportivo-san-inazio', 'Bilbao', 'Bizkaia',
   'Calle Arturo Campión, 8, 48015 Bilbao', 43.2799441, -2.9609756, false,
   '+34 94 452 15 60', '', 'https://www.bilbaokirolak.eus/',
   '8 pistas de pádel cubiertas', true, 'césped artificial', 'Web Bilbao Kirolak / App', true, false,
   false, 'pendiente_verificacion',
   'Bilbao: polideportivo municipal con 8 pistas de pádel cubiertas (Bilbao Kirolak).'),
  ('Polideportivo Zorroza (Bilbao Kirolak)', 'polideportivo-zorroza', 'Bilbao', 'Bizkaia',
   'C/ Martínez Rivas, s/n, 48013 Bilbao (Zorroza)', 43.2786737, -2.9751249, false,
   '+34 944 39 92 00', '', 'https://www.bilbaokirolak.eus/',
   '2 pistas de pádel cubiertas', true, 'césped artificial', 'Web Bilbao Kirolak / App', false, false,
   false, 'pendiente_verificacion',
   'Bilbao: pistas municipales de pádel del polideportivo de Zorroza.'),
  ('Polideportivo Miribilla (Bilbao Kirolak)', 'polideportivo-miribilla', 'Bilbao', 'Bizkaia',
   'Mina San Luis, s/n, 48003 Bilbao', 43.2534589, -2.9295048, false,
   '+34 944 15 14 22', '', 'https://www.bilbaokirolak.eus/',
   'Pistas de pádel cubiertas', true, 'césped artificial', 'Web Bilbao Kirolak / App', false, false,
   false, 'pendiente_verificacion',
   'Bilbao: pistas municipales de pádel en el polideportivo de Miribilla.'),
  ('Azkuna Zentroa (Alhóndiga)', 'azkuna-zentroa', 'Bilbao', 'Bizkaia',
   'Plaza Arriquibar, 4, 48010 Bilbao', 43.2596949, -2.9371186, false,
   '+34 944 01 40 14', '', 'https://www.azkunazentroa.eus/',
   '2 pistas de pádel cubiertas', true, 'césped artificial', 'Web Propia / Teléfono', false, false,
   false, 'pendiente_verificacion',
   'Bilbao: centro cultural y deportivo municipal con pistas de pádel cubiertas.')
on conflict (slug) do nothing;