-- ============================================================
-- PADELORGANIZERS.COM — Fase 7 directorio: Palma de Mallorca
-- 10 clubes/escuelas reales de Palma, geocodificados
-- con Photon/OSM.
-- Idempotente: reejecutable sin duplicar (ON CONFLICT slug).
-- ============================================================

insert into public.clubes
  (name, slug, city, province, address, latitude, longitude, geo_approx,
   phone, email, website, courts, indoor, grass, booking_platform,
   has_school, has_shop, is_verified, status, description)
values
  ('Padel Club Mallorca', 'padel-club-mallorca', 'Palma de Mallorca', 'Islas Baleares',
   'Carrer George Sand, 40, 07007 Palma de Mallorca', 39.5739162, 2.6799347, false,
   '+34 669 599 012', '', 'https://padelclubmallorca.com/',
   '8 pistas dobles (césped azul WPT)', false, 'césped azul WPT', 'Playtomic', true, false,
   false, 'pendiente_verificacion',
   'Palma: 8 pistas dobles de césped azul WPT al aire libre.'),
  ('Pins Padel Club', 'pins-padel-club', 'Palma de Mallorca', 'Islas Baleares',
   'Carrer Lluís Ferbal, 7, 07014 Palma de Mallorca', 39.5750339, 2.6189783, false,
   '+34 971 450 574', 'info@pinspadelclub.es', 'https://www.pinspadelclub.es/',
   '16 pistas (14 dobles, 9 cubiertas, 2 individuales)', true, 'sintético', 'Web Propia / Playtomic', true, false,
   false, 'pendiente_verificacion',
   'Palma: club con 16 pistas (14 dobles, 9 cubiertas) en Sa Teulera.'),
  ('Palma Padel', 'palma-padel', 'Palma de Mallorca', 'Islas Baleares',
   'Carrer Castellà la Manxa, 6, 07013 Palma de Mallorca', 39.5855697, 2.6227757, false,
   '', '', 'https://palmapadel.es/',
   '12 pistas dobles (4 cubiertas) + 4 individuales', true, 'sintético', 'Playtomic', true, false,
   false, 'pendiente_verificacion',
   'Palma: 12 pistas dobles (4 cubiertas) junto al estadio Son Moix.'),
  ('Mallorca Pádel Indoor', 'mallorca-padel-indoor', 'Palma de Mallorca', 'Islas Baleares',
   'Carrer Gremi Velluters, 19, 07009 Son Castelló, Palma de Mallorca', 39.6034954, 2.6580906, false,
   '+34 971 678 900', '', 'https://www.mallorcapadelindoor.com/',
   '6 pistas indoor', true, 'sintético', 'Playtomic / Web Propia', true, false,
   false, 'pendiente_verificacion',
   'Palma: 6 pistas indoor en el polígono de Son Castelló.'),
  ('Padel La Salle', 'padel-la-salle', 'Palma de Mallorca', 'Islas Baleares',
   'Camí de Son Rapinya, 29, 07013 Palma de Mallorca', 39.5824439, 2.6200799, false,
   '', '', 'https://www.playtomic.app/',
   '4 pistas dobles outdoor', false, 'sintético', 'Playtomic', true, false,
   false, 'pendiente_verificacion',
   'Palma: polideportivo La Salle con 4 pistas outdoor.'),
  ('Fit Point Pádel', 'fit-point-padel', 'Palma de Mallorca', 'Islas Baleares',
   'Carrer Son Morro, 10, Pol. Son Morro, 07007 Palma de Mallorca', 39.5743309, 2.6884039, false,
   '+34 971 127 520', '', 'https://fitpointpadel.es/',
   'Pistas cubiertas', true, 'sintético', 'Web Propia / Playtomic', true, false,
   false, 'pendiente_verificacion',
   'Palma: club con pistas cubiertas en el Pol. Son Morro.'),
  ('Padel Factory Son Castelló', 'padel-factory-son-castello', 'Palma de Mallorca', 'Islas Baleares',
   'Carrer Gremi Teixidors, 3, 07009 Son Castelló, Palma de Mallorca', 39.5977773, 2.6666848, false,
   '', '', 'https://www.padelfactory.es/',
   'Pistas de alta calidad', true, 'sintético', 'Playtomic', true, false,
   false, 'pendiente_verificacion',
   'Palma: club de la red Padel Factory en el polígono de Son Castelló.'),
  ('Pádel Indoor La Porciúncula', 'padel-indoor-la-porciuncula', 'Palma de Mallorca', 'Islas Baleares',
   'Camí del Palmer, 16, 07600 Platja de Palma', 39.5147098, 2.7637585, false,
   '+34 722 63 42 71', 'info@padelindoorlaporciuncula.com', 'https://playtomic.app/',
   '10 pistas indoor', true, 'sintético', 'Playtomic', true, false,
   false, 'pendiente_verificacion',
   'Palma: 10 pistas indoor en Playa de Palma, con escuela.'),
  ('Patronato Palma', 'patronato-palma', 'Palma de Mallorca', 'Islas Baleares',
   'Carrer Montevideo, 6, 07006 Palma de Mallorca', 39.564335, 2.6639782, false,
   '', '', 'https://www.playtomic.app/',
   '3 pistas dobles + 1 individual', false, 'sintético', 'Playtomic', true, false,
   false, 'pendiente_verificacion',
   'Palma: club céntrico con 3 pistas dobles.'),
  ('Tenis y Pádel Son Rigo', 'tenis-y-padel-son-rigo', 'Palma de Mallorca', 'Islas Baleares',
   'Carrer de la Mar del Japó, 2, 07610 Platja de Palma', 39.5235614, 2.7470408, false,
   '', '', 'https://www.playtomic.app/',
   'Pistas de pádel + tenis', false, 'sintético', 'Playtomic', true, false,
   false, 'pendiente_verificacion',
   'Palma: club de tenis y pádel en la zona de Son Rigo.')
on conflict (slug) do nothing;