-- ============================================================
-- PADELORGANIZERS.COM — Fase 4 directorio: Barcelona y área metropolitana
-- 10 clubes/escuelas reales (8 Barcelona ciudad + 2 L'Hospitalet),
-- geocodificados con Photon/OSM.
-- Idempotente: reejecutable sin duplicar (ON CONFLICT slug).
-- ============================================================

insert into public.clubes
  (name, slug, city, province, address, latitude, longitude, geo_approx,
   phone, email, website, courts, indoor, grass, booking_platform,
   has_school, has_shop, is_verified, status, description)
values
  ('Vall Parc', 'vall-parc', 'Barcelona', 'Barcelona',
   'Carretera de l''Arrabassada, 107-127, 08035 Barcelona', 41.4182993, 2.1386325, false,
   '+34 932 12 67 89 / 695 299 455', 'info@vallparc.com', 'https://www.vallparc.com/',
   '19 pistas (14 outdoor, 5 indoor)', true, 'sintético', 'Playtomic / Web Propia', true, true,
   false, 'pendiente_verificacion',
   'El club de raqueta más grande de Barcelona: 19 pistas de pádel (14 outdoor, 5 indoor), tenis, gimnasio y escuela con más de 800 alumnos, al pie del Tibidabo.'),
  ('Nick Club Pádel Barcelona', 'nick-club-padel-barcelona', 'Barcelona', 'Barcelona',
   'Carrer de Campoamor, 66, 08031 Barcelona', 41.4355296, 2.1541484, false,
   '+34 605 67 13 55', 'hola@nickpadel.com', 'https://www.nickpadel.com/',
   '8 pistas panorámicas (1 central CUPRA)', true, 'panorámico', 'Playtomic', true, false,
   false, 'pendiente_verificacion',
   'Club con 8 pistas panorámicas en Horta-Guinardó y pista central CUPRA.'),
  ('Artós Sports Club', 'artos-sports-club', 'Barcelona', 'Barcelona',
   'Carrer dels Vergós, 67, 08017 Barcelona', 41.399678, 2.1311927, false,
   '+34 931 162 118 / 662 602 833', 'info@artossportsclub.com', 'https://artossportsclub.com/',
   '11 pistas outdoor (1 panorámica)', false, 'sintético', 'Web Propia / WhatsApp', true, false,
   false, 'pendiente_verificacion',
   'Club de pádel y fútbol en Sarrià con 11 pistas outdoor y escuela de pádel.'),
  ('Indoor Pádel Barcelona (22@)', 'indoor-padel-barcelona-22', 'Barcelona', 'Barcelona',
   'Carrer de Veneçuela, 78, 08019 Barcelona', 41.4113742, 2.2092793, false,
   '+34 932 66 35 12', 'gerencia@ipadelbarcelona.com', 'https://www.ipadelbarcelona.com/',
   '5 pistas indoor (distrito 22@)', true, 'sintético', 'App Propia / Web', true, true,
   false, 'pendiente_verificacion',
   'El primer y único padel indoor en el núcleo urbano de Barcelona, en el distrito 22@ (Sant Martí).'),
  ('Uno Padel Teixonera', 'uno-padel-teixonera', 'Barcelona', 'Barcelona',
   'Carrer de la Granja Vella, 10, 08035 Barcelona', 41.4269126, 2.1467277, false,
   '+34 93 101 09 33 / 667 16 29 07', '', 'https://www.unopadel.com/',
   '9 pistas de pádel', true, 'sintético', 'Playtomic', true, false,
   false, 'pendiente_verificacion',
   'Centro UnoPadel en la Ciutat Deportiva Vall d''Hebron-Teixonera con 9 pistas.'),
  ('Padel 7 Sant Andreu', 'padel-7-sant-andreu', 'Barcelona', 'Barcelona',
   'Carrer de Bonaventura Gispert, 1, 08020 Barcelona', 41.4259303, 2.1980254, false,
   '+34 627 944 548', 'padel7esportiu@gmail.com', 'https://padel7santmarti.com/',
   'Pistas outdoor e indoor · 8.200 m²', true, 'sintético', 'Web Propia / Teléfono', true, false,
   false, 'pendiente_verificacion',
   'Sede original del grupo Padel 7 en Sant Andreu.'),
  ('Padel 7 Sant Martí', 'padel-7-sant-marti', 'Barcelona', 'Barcelona',
   'Carrer de Puigcerdà, 111, 08019 Barcelona', 41.4137828, 2.2113413, false,
   '+34 627 944 548', 'padel7esportiu@gmail.com', 'https://padel7santmarti.com/',
   '11 pistas indoor', true, 'sintético', 'Web Propia / Teléfono', true, false,
   false, 'pendiente_verificacion',
   'Sede de Padel 7 en Sant Martí con 11 pistas indoor.'),
  ('Bela Padel Center Barcelona', 'bela-padel-center-barcelona', 'Barcelona', 'Barcelona',
   'Avinguda del Parc Logístic, 28, 08040 Barcelona', 41.3410341, 2.126219, false,
   '+34 636 242 557', 'info.bcn@belapadelcenter.com', 'https://belapadelcenter.com/',
   '20 pistas (9 indoor, 11 outdoor)', true, 'sintético', 'Playtomic', true, true,
   false, 'pendiente_verificacion',
   'Firma de Fernando Belasteguín: 20 pistas de última generación (9 indoor, 11 outdoor) en la Zona Franca de Barcelona.'),
  ('Padel Top Club (Top Padel Barcelona)', 'padel-top-barcelona', 'L''Hospitalet de Llobregat', 'Barcelona',
   'Carretera del Mig, 39, 08907 L''Hospitalet de Llobregat', 41.357904, 2.1128575, false,
   '', '', '',
   '5 pistas indoor + squash y gimnasio', true, 'sintético', 'Playtomic', false, true,
   false, 'pendiente_verificacion',
   'Uno de los primeros clubes indoor de Barcelona, en el área de Bellvitge (L''Hospitalet).'),
  ('Pàdel Indoor L''Hospitalet', 'padel-indoor-hospitalet', 'L''Hospitalet de Llobregat', 'Barcelona',
   'Carrer del Cobalt, 85, 08907 L''Hospitalet de Llobregat', 41.3581349, 2.1087007, false,
   '+34 635 721 728', 'info@padelindoorhospitalet.com', 'https://padelindoorhospitalet.com/',
   '24 pistas indoor', true, 'sintético', 'Web Propia / Playtomic', true, false,
   false, 'pendiente_verificacion',
   'Gran centro indoor con 24 pistas en el polígono industrial de Bellvitge (L''Hospitalet).')
on conflict (slug) do nothing;