-- ============================================================
-- PADELORGANIZERS.COM — Fase 7 directorio: Murcia
-- 10 clubes/escuelas reales de Murcia capital y pedanías,
-- geocodificados con Photon/OSM.
-- Idempotente: reejecutable sin duplicar (ON CONFLICT slug).
-- ============================================================

insert into public.clubes
  (name, slug, city, province, address, latitude, longitude, geo_approx,
   phone, email, website, courts, indoor, grass, booking_platform,
   has_school, has_shop, is_verified, status, description)
values
  ('Sport Joven Futura', 'sport-joven-futura', 'Murcia', 'Murcia',
   'Calle Escritor Francisco Alemán Sainz, 1, 30100 Espinardo, Murcia', 38.0036602, -1.1566569, false,
   '+34 631 698 079', 'sportj.futura@gmail.com', 'https://www.padelsportjovenfutura.com/',
   '8 pistas panorámicas al aire libre', false, 'panorámico', 'Web Propia / Teléfono', true, true,
   false, 'pendiente_verificacion',
   'Murcia: club con 8 pistas panorámicas exteriores en Espinardo, con escuela y tienda.'),
  ('Club de Pádel Nueva Flota', 'club-de-padel-nueva-flota', 'Murcia', 'Murcia',
   'Calle Cuatro Caminos, 19, 30007 Murcia', 37.9959594, -1.1175888, false,
   '+34 868 968 625', 'info@clubdepadelnuevaflota.com', 'https://www.clubdepadelnuevaflota.com/',
   '6 pistas outdoor de cristal', false, 'sintético', 'Web Propia / Playtomic', true, true,
   false, 'pendiente_verificacion',
   'Murcia: 6 pistas outdoor de cristal con escuela y tienda.'),
  ('Más Que Padel', 'mas-que-padel', 'Murcia', 'Murcia',
   'Carril del Cebadero, 6, 30010 Murcia', 37.9632165, -1.1315388, false,
   '', '', 'https://www.playtomic.app/',
   '7 pistas outdoor', false, 'sintético', 'Playtomic', true, false,
   false, 'pendiente_verificacion',
   'Murcia: 7 pistas de pádel al aire libre con escuela.'),
  ('Club Padel Brothers', 'club-padel-brothers', 'Murcia', 'Murcia',
   'Avenida Mariano Rojas, 9, 30006 Puente Tocinos, Murcia', 37.9970701, -1.1026803, false,
   '', '', 'https://clubpadelbrothers.com/',
   'Pistas outdoor', false, 'sintético', 'Web Propia / Playtomic', true, false,
   false, 'pendiente_verificacion',
   'Murcia: club de pádel en Puente Tocinos.'),
  ('Atrium Padel', 'atrium-padel', 'Murcia', 'Murcia',
   'Avenida de Alicante, 241, 30007 Murcia', 37.9936522, -1.1168789, false,
   '+34 968 23 78 10', '', 'https://www.atriumpadel.com/',
   '6 pistas outdoor con LED + restaurante', false, 'sintético', 'Web Propia / Playtomic', true, false,
   false, 'pendiente_verificacion',
   'Murcia: 6 pistas al aire libre con iluminación LED y restaurante en Av. de Alicante.'),
  ('Pádel Norte Espinardo', 'padel-norte-espinardo', 'Murcia', 'Murcia',
   'Calle Monseñor José Manuel Lorca, 37, 30100 Espinardo, Murcia', 38.0104378, -1.1501887, false,
   '+34 968 30 41 41', '', 'https://www.padelnorteespinardo.com/',
   '11 pistas outdoor', false, 'sintético', 'Web Propia / Playtomic', true, false,
   false, 'pendiente_verificacion',
   'Murcia: 11 pistas de pádel al aire libre en Espinardo.'),
  ('Murcia Club de Tenis 1919', 'murcia-club-de-tenis-1919', 'Murcia', 'Murcia',
   'Calle Cronista Carlos Valcárcel, 5, 30008 Murcia', 37.9933184, -1.1341231, false,
   '+34 968 22 04 77', 'info@murciaclubdetenis.com', 'https://mct1919.es/',
   '4 pistas de pádel + 15 de tenis', false, 'césped sintético', 'Web Socios / Teléfono', true, false,
   false, 'pendiente_verificacion',
   'Club histórico (1919) con 4 pistas de pádel y 15 de tenis.'),
  ('M2 Pádel Indoor', 'm2-padel-indoor', 'Murcia', 'Murcia',
   'Avenida José Bautista Frutos, 8, 30100 Murcia', 38.030887, -1.1675334, false,
   '+34 685 83 67 95', '', 'https://www.playtomic.app/',
   '6 pistas indoor', true, 'sintético', 'Playtomic', true, false,
   false, 'pendiente_verificacion',
   'Murcia: 6 pistas indoor con escuela y actividades en Av. José Bautista Frutos.'),
  ('Moon Padel Indoor', 'moon-padel-indoor', 'Murcia', 'Murcia',
   'Avenida de Era Alta, 21, 30166 Murcia', 37.972446, -1.1717884, false,
   '+34 621 28 86 35', '', 'https://www.moonpadel.com/',
   '5 pistas (1 WPT indoor, 1 indoor, 3 exterior)', true, 'sintético', 'Playtomic', true, false,
   false, 'pendiente_verificacion',
   'Murcia: pistas WPT e indoor en la pedanía de Era Alta / Nonduermas.'),
  ('Club PadelOn', 'club-padelon', 'Murcia', 'Murcia',
   'Avenida Silva Muñoz, 30161 Llano de Brujas, Murcia', 38.0076753, -1.070853, false,
   '+34 968 85 70 79', '', 'https://www.padelon.es/',
   '7 pistas outdoor', false, 'sintético', 'Playtomic', true, false,
   false, 'pendiente_verificacion',
   'Murcia: club con 7 pistas en Llano de Brujas.')
on conflict (slug) do nothing;