-- ============================================================
-- PADELORGANIZERS.COM — Fase 5 directorio: Valencia y Sevilla
-- 10 clubes/escuelas reales por ciudad (Valencia + metro l'Horta,
-- Sevilla + Dos Hermanas), geocodificados con Photon/OSM.
-- Idempotente: reejecutable sin duplicar (ON CONFLICT slug).
-- ============================================================

-- Valencia ------------------------------------------------
insert into public.clubes
  (name, slug, city, province, address, latitude, longitude, geo_approx,
   phone, email, website, courts, indoor, grass, booking_platform,
   has_school, has_shop, is_verified, status, description)
values
  ('Sportcity Valencia (BamVolea)', 'sportcity-valencia', 'Massanassa', 'Valencia',
   'Carrer del Poliesportiu, 2, 46470 Massanassa', 39.4110157, -0.3905469, false,
   '+34 96 113 03 50', '', 'https://sportcityvalencia.com/',
   '30 pistas (20 indoor, 10 outdoor)', true, 'sintético', 'Playtomic / Web Propia', true, true,
   false, 'pendiente_verificacion',
   'De la red BamVolea: 30 pistas (20 indoor y 10 outdoor). El 2º club de pádel más grande del mundo y el mayor de la Comunitat Valenciana. Frente a Ikea.'),
  ('Pádel City VLC', 'padel-city-vlc', 'Valencia', 'Valencia',
   'Valencia', 39.4699, -0.3763, true,
   '+34 962 05 41 67', 'info@padelcv.com', 'https://padelcv.com/',
   'Pistas indoor panorámicas', true, 'panorámico', 'Web Propia / Teléfono', true, false,
   false, 'pendiente_verificacion',
   'Club indoor de referencia en Valencia, con pistas panorámicas y sede del grupo deportivo PadelCV.'),
  ('7 Pádel', '7-padel-valencia', 'Valencia', 'Valencia',
   'Carrer dels Llanterners, 6, Vara de Quart, 46014 València', 39.4611585, -0.408754, false,
   '+34 615 07 10 10', 'info@7padel.com', 'https://www.7padel.com/',
   '11 pistas indoor (13 m de altura libre)', true, 'sintético', 'Web Propia / WhatsApp', true, true,
   false, 'pendiente_verificacion',
   'Club indoor en el polígono Vara de Quart con 11 pistas de 13 metros de altura libre, tienda y escuela.'),
  ('CM Valencia Tennis Center (Malvarrosa)', 'cm-valencia-tennis-center', 'Valencia', 'Valencia',
   'Carrer de Vicent la Roda, s/n, 46011 València (Malvarrosa)', 39.4794127, -0.3277079, false,
   '+34 609 690 090 / 650 047 962', 'gerente@cmvalenciatenniscenter.com', 'https://www.cmvalenciatenniscenter.com/',
   '8 pistas de pádel + 10 de tenis', false, 'césped sintético', 'Web Propia / WhatsApp', true, false,
   false, 'pendiente_verificacion',
   'Club de tenis y pádel junto a la playa de la Patacona, en las instalaciones del colegio Escoles Pies de Malvarrosa.'),
  ('Forus Rambleta Valencia', 'forus-rambleta-valencia', 'Valencia', 'Valencia',
   'Carrer de Pius IX, s/n, 46017 València (La Rambleta)', 39.4434254, -0.3970499, false,
   '+34 960 663 825', '', 'https://rambleta.forus.es/',
   'Pistas de pádel exteriores', false, 'sintético', 'Playtomic / Web Forus', true, false,
   false, 'pendiente_verificacion',
   'Centro deportivo municipal gestionado por Forus, con pistas de pádel, piscina cubierta, spa y gran oferta fitness.'),
  ('SUMA Pádel Club Patacona', 'suma-padel-club-patacona', 'Valencia', 'Valencia',
   'Passeig Marítim de la Patacona, 46113 Alboraya', 39.4849804, -0.3249837, false,
   '+34 963 20 51 80', '', 'https://www.sumafitnessclub.com/patacona/',
   '4 pistas exteriores', false, 'sintético', 'Playtomic', true, false,
   false, 'pendiente_verificacion',
   'Club de pádel a 100 metros del paseo de la playa de la Patacona, con escuela y reservas por Playtomic.'),
  ('Padel Galaxy', 'padel-galaxy-benetusser', 'Benetússer', 'Valencia',
   'Carrer del Camí de l''Orba, 8, 46910 Benetússer', 39.4209075, -0.3941681, false,
   '', '', '',
   '8 pistas panorámicas', true, 'panorámico', 'Playtomic', true, false,
   false, 'pendiente_verificacion',
   'Club con 8 pistas panorámicas de última generación a pocos minutos de Valencia, con torneos y escuela.'),
  ('Flow Pádel Club', 'flow-padel-club-paterna', 'Paterna', 'Valencia',
   'Carrer de la Ciutat de Sevilla, 43, PI Fuente del Jarro, 46988 Paterna', 39.5187273, -0.463549, false,
   '', '', '',
   '7 pistas indoor', true, 'sintético', 'Playtomic', true, false,
   false, 'pendiente_verificacion',
   'Club con 7 pistas indoor en el polígono Fuente del Jarro (Paterna).'),
  ('Padel Club Valencia', 'padel-club-valencia', 'La Pobla de Vallbona', 'Valencia',
   'Ctra. Valencia-Ademuz, Km 20,9, 46185 La Pobla de Vallbona', 39.5907339, -0.5532185, true,
   '', '', 'https://padelclubvalencia.es/',
   '9 pistas indoor de cristal (Mondo WPT)', true, 'césped Mondo / moqueta', 'Web Propia', true, false,
   false, 'pendiente_verificacion',
   'Club indoor de referencia en l''Horta Nord con 9 pistas de cristal, ligas y escuela de menores.'),
  ('SUMA Pádel Club Alfafar', 'suma-padel-club-alfafar', 'Alfafar', 'Valencia',
   'Alfafar, Valencia', 39.4200749, -0.3891355, true,
   '+34 963 20 51 80', '', 'https://sumapadelclub.com/',
   '15 pistas (11 indoor, 4 exteriores) + 2 de tenis', true, 'panorámico', 'Playtomic', true, true,
   false, 'pendiente_verificacion',
   'Club con 15 pistas panorámicas (11 indoor), 2 de tenis, escuela y centro fitness SUMA.'),

  -- Sevilla ------------------------------------------------
  ('Icónico Sports & Social Club', 'iconico-sports-club-sevilla', 'Sevilla', 'Sevilla',
   'Calle Economía, 11-13, Pol. Store, 41007 Sevilla', 37.394221, -5.9479863, false,
   '+34 722 239 744', 'info@iconicosports.com', 'https://www.iconicosports.com/',
   'Pistas panorámicas · 9.000 m²', true, 'panorámico', 'Playtomic / Web Propia', true, true,
   false, 'pendiente_verificacion',
   'Referente del pádel en Sevilla: 9.000 m² con pistas panorámicas de última generación, escuela, restauración y eventos.'),
  ('El Remate Pádel Club', 'el-remate-padel-club', 'Sevilla', 'Sevilla',
   'Avenida de Montes Sierra, 38, 41007 Sevilla', 37.3956621, -5.9493939, false,
   '+34 619 817 451 / 658 090 639', '', 'https://elrematepadelclub.com/',
   '11 pistas indoor de cristal cubiertas', true, 'cristal', 'Web Propia / Teléfono', true, false,
   false, 'pendiente_verificacion',
   'Club con 11 pistas indoor de cristal y una de las escuelas de pádel más prestigiosas de Sevilla.'),
  ('Iron Padel Indoor Sevilla', 'iron-padel-indoor-sevilla', 'Sevilla', 'Sevilla',
   'Calle Nivel, 10 (Polígono Store), 41008 Sevilla', 37.4104718, -5.9604976, false,
   '', '', '',
   '4 pistas indoor climatizadas', true, 'sintético', 'Playtomic', true, false,
   false, 'pendiente_verificacion',
   'Club indoor climatizado en el Polígono Store, con escuela de pádel.'),
  ('IOPadel', 'iopadel-sevilla', 'Sevilla', 'Sevilla',
   'Avenida de la Prensa, 36, 41007 Sevilla', 37.3897757, -5.9541344, false,
   '', '', '',
   '6 pistas (4 cubiertas, 2 exteriores)', true, 'sintético', 'Playtomic', true, false,
   false, 'pendiente_verificacion',
   'Club con 6 pistas de pádel (4 cubiertas y 2 exteriores) en Sevilla Este.'),
  ('Galisport Happiness Club', 'galisport-happiness-club', 'Sevilla', 'Sevilla',
   'Cardenal Bueno Monreal, s/n (Av. de la Palmera), 41013 Sevilla', 37.3679474, -5.986178, false,
   '', '', '',
   'Pistas de pádel', false, 'sintético', 'Web Propia', true, false,
   false, 'pendiente_verificacion',
   'Club social y deportivo en la zona de la Palmera con pistas de pádel.'),
  ('Santé Sport & Social Club', 'sante-sport-social-club', 'Sevilla', 'Sevilla',
   'Avenida del Deporte, 12, 41020 Sevilla (Sevilla Este)', 37.3897486, -5.914019, false,
   '+34 955 94 05 72', '', 'https://www.santesportsocialclub.es/',
   '6 pistas de pádel (4 indoor) + fútbol 7', true, 'sintético', 'App / Web Propia', true, false,
   false, 'pendiente_verificacion',
   'Club privado en Sevilla Este con 6 pistas de pádel (4 indoor), piscinas, fitness y amplia zona social.'),
  ('Real Club de Tenis Betis', 'real-club-tenis-betis', 'Sevilla', 'Sevilla',
   'Avenida Ramón Carande, 4, 41013 Sevilla', 37.369653, -5.9780869, false,
   '+34 954 233 622', '', 'https://www.tenisbetis.com/',
   '2 pistas de pádel + 6 de tenis', false, 'cristal / césped artificial', 'Web Socios / Teléfono', true, false,
   false, 'pendiente_verificacion',
   'Histórico club sevillano (1929) con pistas de pádel y tenis, sede de la Copa Sevilla Challenger (ATP).'),
  ('Sevilla Padel Experience', 'sevilla-padel-experience', 'Sevilla', 'Sevilla',
   'Cardenal Bueno Monreal, s/n, 41013 Sevilla', 37.3684719, -5.9833723, false,
   '', '', 'https://sevillapadelexperience.com/',
   'Pistas panorámicas + estancias de entrenamiento', true, 'panorámico', 'Web Propia', true, false,
   false, 'pendiente_verificacion',
   'Club centrado en formación de alto nivel y padel tourism, con pistas panorámicas en zona Cardenal Bueno Monreal.'),
  ('Panoramic Padel Club', 'panoramic-padel-club', 'Sevilla', 'Sevilla',
   'Sevilla', 37.3891, -5.9845, true,
   '', '', '',
   '10 pistas (indoor y outdoor)', true, 'panorámico', 'Playtomic', true, false,
   false, 'pendiente_verificacion',
   'Club de pádel de referencia en Sevilla con pistas panorámicas y escuela.'),
  ('Infinity Indoor', 'infinity-indoor-dos-hermanas', 'Dos Hermanas', 'Sevilla',
   'Calle Adalid Domingo Ledesma, 9, 41703 Dos Hermanas (Sevilla)', 37.3130425, -5.9757148, false,
   '+34 955 54 75 77', '', 'https://infinityindoor.com/',
   '8 pistas indoor', true, 'sintético', 'Playtomic / Web Propia', true, false,
   false, 'pendiente_verificacion',
   'Centro indoor con 8 pistas y academia de pádel en Dos Hermanas (metro de Sevilla).')
on conflict (slug) do nothing;