-- ============================================================
-- PADELORGANIZERS.COM — Fase 7 directorio: Málaga
-- 10 clubes/escuelas reales de Málaga, geocodificados
-- con Photon/OSM.
-- Idempotente: reejecutable sin duplicar (ON CONFLICT slug).
-- ============================================================

insert into public.clubes
  (name, slug, city, province, address, latitude, longitude, geo_approx,
   phone, email, website, courts, indoor, grass, booking_platform,
   has_school, has_shop, is_verified, status, description)
values
  ('Finura Padel & Gym', 'finura-padel-gym', 'Málaga', 'Málaga',
   'Calle Pascal, 20, Pol. Indiana-Villarosa, 29004 Málaga', 36.670511, -4.4701779, false,
   '+34 682 453 827', 'info@finurapadelgym.com', 'https://www.finurapadelgym.com/',
   '7 pistas cubiertas panorámicas', true, 'panorámico', 'Web Propia / Teléfono', true, false,
   false, 'pendiente_verificacion',
   'Málaga: 7 pistas cubiertas panorámicas y gimnasio en el Pol. Indiana-Villarosa.'),
  ('GM Padel Indoor', 'gm-padel-indoor', 'Málaga', 'Málaga',
   'Calle Bodegueros, 42, 29006 Málaga', 36.7055046, -4.4484524, false,
   '+34 645 855 777', '', 'https://gmpadelindoor.es/',
   '5 pistas indoor de cristal', true, 'sintético', 'Playtomic', true, false,
   false, 'pendiente_verificacion',
   'Málaga: club indoor con 5 pistas de cristal en El Perchel.'),
  ('Padel Picasso', 'padel-picasso', 'Málaga', 'Málaga',
   'Calle Hilera, 18, 29007 Málaga', 36.718394, -4.4364968, false,
   '+34 744 62 36 83', '', 'https://www.playtomic.app/',
   '4 pistas (cubiertas y aire libre)', true, 'sintético', 'Playtomic', true, false,
   false, 'pendiente_verificacion',
   'Málaga: club con 4 pistas de pádel cerca del centro histórico.'),
  ('Ático Padel Club', 'atico-padel-club', 'Málaga', 'Málaga',
   'Plaza de Toros Vieja, 5, 29002 Málaga', 36.7121245, -4.4271193, false,
   '', '', 'https://www.playtomic.app/',
   'Pistas indoor y outdoor', true, 'sintético', 'Playtomic', false, false,
   false, 'pendiente_verificacion',
   'Málaga: club de pádel en la zona de la Malagueta.'),
  ('Pádel Deportes Málaga', 'padel-deportes-malaga', 'Málaga', 'Málaga',
   'Calle Caballito de Mar, 8, 29006 Málaga', 36.7056296, -4.4685737, false,
   '', '', 'https://www.padeldeportes.com/',
   '6 pistas cubiertas', true, 'sintético', 'Playtomic', true, false,
   false, 'pendiente_verificacion',
   'Málaga: centro de 6 pistas cubiertas en El Perchel.'),
  ('Vals Sport Cónsul', 'vals-sport-consul', 'Málaga', 'Málaga',
   'Calle Sófocles, 11, 29010 Málaga', 36.7231702, -4.4806406, false,
   '+34 951 57 81 69', '', 'https://valssport.com/',
   '17 pistas de pádel', true, 'sintético', 'Web Propia / Playtomic', true, false,
   false, 'pendiente_verificacion',
   'Málaga: gran complejo Vals Sport con 17 pistas de pádel en El Cónsul.'),
  ('Vals Sport Teatinos', 'vals-sport-teatinos', 'Málaga', 'Málaga',
   'Calle Mesonero Romanos, 11, 29010 Málaga', 36.7215929, -4.460312, false,
   '+34 951 57 81 69', '', 'https://valssport.com/',
   '8 pistas de pádel', true, 'sintético', 'Web Propia / Playtomic', true, false,
   false, 'pendiente_verificacion',
   'Málaga: club de la red Vals Sport con 8 pistas en Teatinos.'),
  ('Vals Sport Ave María', 'vals-sport-ave-maria', 'Málaga', 'Málaga',
   'Avenida Sor Teresa Prat, 53, 29003 Málaga', 36.6962035, -4.4420403, false,
   '+34 951 57 81 69', '', 'https://valssport.com/',
   '11 pistas de pádel', true, 'sintético', 'Web Propia / Playtomic', true, false,
   false, 'pendiente_verificacion',
   'Málaga: club Vals Sport con 11 pistas de pádel junto a la zona Ave María.'),
  ('Club Deportivo León 13', 'club-deportivo-leon-13', 'Málaga', 'Málaga',
   'Calle Miguel Sel Gómez de la Cruz, 2, 29018 Málaga', 36.7297156, -4.37515, false,
   '+34 952 04 35 93', '', 'https://www.leon13malaga.com/',
   '13 pistas de pádel + tenis', true, 'sintético', 'Web Propia / Teléfono', true, false,
   false, 'pendiente_verificacion',
   'Málaga: club con 13 pistas de pádel, tenis y gimnasio en Cerrado de Calderón.'),
  ('Club de Pádel Miraflores', 'club-de-padel-miraflores', 'Málaga', 'Málaga',
   'Calle Francisco Guillón, 11, 29018 Málaga', 36.7262352, -4.3745006, false,
   '+34 654 82 51 11', '', 'https://www.playtomic.app/',
   'Pistas de pádel', true, 'sintético', 'Playtomic', true, false,
   false, 'pendiente_verificacion',
   'Málaga: club de pádel con escuela en Cerrado de Calderón / Miraflores.')
on conflict (slug) do nothing;