-- ============================================================
-- PADELORGANIZERS.COM — Fase 8 directorio: 15 grandes ciudades
-- Las Palmas y Telde, Alicante, Córdoba, Valladolid, Gijón,
-- L'Hospitalet de Llobregat, A Coruña (Cambre/Culleredo/Bergondo),
-- Vitoria-Gasteiz, Elche, Granada (Churriana de la Vega),
-- Terrassa, Badalona, Sabadell, Oviedo y Cartagena.
-- Completa la cobertura de las 25 mayores ciudades de España.
-- geo_approx = true (coordenadas aproximadas por ciudad/zona).
-- Idempotente: reejecutable sin duplicar (ON CONFLICT slug).
-- ============================================================

insert into public.clubes
  (name, slug, city, province, address, latitude, longitude, geo_approx,
   phone, email, website, courts, indoor, grass, booking_platform,
   has_school, has_shop, is_verified, status, description)
values
  -- Las Palmas de Gran Canaria / Telde
  ('El Drago Pádel Club', 'el-drago-padel-club', 'Las Palmas de Gran Canaria', 'Las Palmas',
   'Av. de Escaleritas, s/n, 35011 Las Palmas de Gran Canaria', 28.1235, -15.4363, true,
   '+34 928 00 00 00', 'info@eldragopadel.es', '',
   '11 pistas de cristal (1 panorámica)', true, 'sintético', 'Playtomic', true, false,
   false, 'pendiente_verificacion',
   'Las Palmas de Gran Canaria: 11 pistas de cristal, una de ellas panorámica.'),
  ('Gran Canaria Pádel Indoor', 'gran-canaria-padel-indoor', 'Telde', 'Las Palmas',
   'Calle Modem 18, Polígono Industrial Jínamar, 35220 Telde', 27.9905, -15.415, true,
   '+34 928 00 00 00', 'info@grancanariapadelindoor.es', '',
   '8 pistas cubiertas (1 panorámica, 1 individual)', true, 'sintético', 'Playtomic', true, true,
   false, 'pendiente_verificacion',
   'Telde: 8 pistas cubiertas con escuela propia y ligas de empresa.'),
  ('Club La Calzada', 'club-la-calzada', 'Las Palmas de Gran Canaria', 'Las Palmas',
   'Ctra. La Calzada, 100, 35011 Las Palmas de Gran Canaria', 28.1155, -15.4355, true,
   '+34 928 35 51 51', '', '',
   '17 pistas outdoor', false, 'sintético', 'Playtomic', true, false,
   false, 'pendiente_verificacion',
   'Las Palmas de Gran Canaria: 17 pistas de pádel al aire libre.'),
  ('Club de Padel Las Palmeras', 'club-de-padel-las-palmeras', 'Las Palmas de Gran Canaria', 'Las Palmas',
   'Calle Dr. Alfonso Chiscano Díaz, s/n, 35019 Las Palmas de Gran Canaria', 28.1316, -15.4418, true,
   '+34 928 00 00 00', '', '',
   '6 pistas outdoor', false, 'sintético', 'Playtomic', false, false,
   false, 'pendiente_verificacion',
   'Las Palmas de Gran Canaria: 6 pistas de pádel al aire libre.'),
  -- Alicante
  ('Padel Club Alicante Indoor', 'padel-club-alicante-indoor', 'Alicante', 'Alicante',
   'Avda Neptuno 15, Polígono Llano del Espartal, 03007 Alicante', 38.3452, -0.481, true,
   '+34 965 00 00 00', 'info@padelclubalicante.com', 'https://www.padelclubalicante.com/',
   '10 pistas (7 indoor, 3 outdoor)', true, 'sintético', 'Playtomic / Web Propia', true, false,
   false, 'pendiente_verificacion',
   'Alicante: 10 pistas (7 indoor y 3 outdoor) con escuela de pádel.'),
  ('Red Padel', 'red-padel-alicante', 'Alicante', 'Alicante',
   'Calle Isla de Corfú, 5, 03003 Alicante', 38.3501, -0.4842, true,
   '+34 965 00 00 00', '', '',
   '7 pistas de pádel', true, 'sintético', 'Playtomic', true, false,
   false, 'pendiente_verificacion',
   'Alicante: 7 pistas de pádel con pista central y ligas.'),
  ('BELA Padel Center Alicante', 'bela-padel-center-alicante', 'Alicante', 'Alicante',
   'Av. Locutor Vicente Hipólito, s/n, 03540 Alicante', 38.3405, -0.4845, true,
   '+34 966 00 00 00', 'info@belapadelcenter.com', 'https://belapadelcenter.com/',
   '14 pistas (7 indoor, 7 outdoor)', true, 'sintético', 'Playtomic', true, true,
   false, 'pendiente_verificacion',
   'Alicante: 14 pistas (indoor y outdoor), restaurante y gimnasio.'),
  ('Alacant Padel Indoor', 'alacant-padel-indoor', 'Alicante', 'Alicante',
   'Polígono Industrial Rabasa, 03006 Alicante', 38.3341, -0.4903, true,
   '+34 965 00 00 00', '', '',
   'Pistas indoor', true, 'sintético', 'Playtomic', true, false,
   false, 'pendiente_verificacion',
   'Alicante: centro de pádel indoor en el Pol. Rabasa.'),
  -- Córdoba
  ('Club de Pádel La Salle', 'club-de-padel-la-salle', 'Córdoba', 'Córdoba',
   'Ctra. de las Ermitas, Nte. Sierra, 14014 Córdoba', 37.8882, -4.7794, true,
   '+34 957 00 00 00', '', '',
   'Pistas de pádel outdoor', false, 'sintético', 'Playtomic', true, false,
   false, 'pendiente_verificacion',
   'Córdoba: club de pádel en Sierra (sede de torneos FIP RISE).'),
  ('Club de Pádel Las Quemadas', 'club-de-padel-las-quemadas', 'Córdoba', 'Córdoba',
   'Ctra. de Trassierra, km 3, 14011 Córdoba', 37.8812, -4.8221, true,
   '+34 957 00 00 00', '', '',
   '7 pistas de pádel', false, 'sintético', 'Playtomic', true, false,
   false, 'pendiente_verificacion',
   'Córdoba: 7 pistas de pádel en la zona de Trassierra.'),
  ('Club Deportivo El Carmen', 'club-deportivo-el-carmen', 'Córdoba', 'Córdoba',
   'Av. del Aeropuerto, s/n, 14012 Córdoba', 37.8934, -4.7768, true,
   '+34 957 00 00 00', '', '',
   '4 pistas de pádel', false, 'sintético', 'Teléfono / Presencial', true, false,
   false, 'pendiente_verificacion',
   'Córdoba: complejo deportivo con 4 pistas de pádel y fútbol.'),
  -- Valladolid
  ('Vip Pádel Valladolid', 'vip-padel-valladolid', 'Valladolid', 'Valladolid',
   'Calle Zanfona, 10, nave 2, 47012 Valladolid', 41.6487, -4.7265, true,
   '+34 983 00 00 00', 'info@vippadelvalladolid.com', '',
   '6 pistas de pádel', true, 'sintético', 'Playtomic', true, true,
   false, 'pendiente_verificacion',
   'Valladolid: 6 pistas con escuela, torneos y quedadas.'),
  ('Valladolid Indoor Padel', 'valladolid-indoor-padel', 'Valladolid', 'Valladolid',
   'Camino Viejo de Simancas, s/n, 47008 Valladolid', 41.6421, -4.7354, true,
   '+34 983 00 00 00', '', '',
   '9 pistas indoor', true, 'sintético', 'Playtomic', true, false,
   false, 'pendiente_verificacion',
   'Valladolid: 9 pistas de pádel cubiertas.'),
  ('Club Raqueta Valladolid', 'club-raqueta-valladolid', 'Valladolid', 'Valladolid',
   'C. Padre José Acosta, 2, 47015 Valladolid', 41.6551, -4.7182, true,
   '+34 983 00 00 00', '', '',
   '9 pistas de pádel', true, 'sintético', 'Playtomic', true, false,
   false, 'pendiente_verificacion',
   'Valladolid: club con 9 pistas de pádel (sede de campeonatos nacionales).'),
  ('Padel Arena Valladolid', 'padel-arena-valladolid', 'Valladolid', 'Valladolid',
   'Polígono San Cristóbal, 47012 Valladolid', 41.6568, -4.6968, true,
   '+34 983 00 00 00', 'info@padelarenavalladolid.com', 'https://www.padelarenavalladolid.com/',
   '6 pistas de pádel', true, 'sintético', 'Playtomic', true, false,
   false, 'pendiente_verificacion',
   'Valladolid: 6 pistas con clases para todos los niveles.'),
  -- Gijón
  ('Norpadel Gijón', 'norpadel-gijon', 'Gijón', 'Asturias',
   'Calle Blas Cabrera y Felipe, Nave 4A, Polígono Porceyo, 33211 Gijón', 43.5324, -5.6611, true,
   '+34 984 10 32 29', 'norpadel@gmail.com', 'https://www.norpadelgijon.com/',
   '7 pistas indoor', true, 'sintético', 'Web Propia / Playtomic', true, false,
   false, 'pendiente_verificacion',
   'Gijón: 7 pistas indoor en el Polígono de Porceyo.'),
  ('Soccer World Gijón', 'soccer-world-gijon', 'Gijón', 'Asturias',
   'Av. de la Argentina, s/n, 33213 Gijón', 43.5281, -5.6863, true,
   '+34 985 00 00 00', '', '',
   '10 pistas (6 cubiertas, 4 exteriores, 1 panorámica)', true, 'sintético', 'Playtomic', true, false,
   false, 'pendiente_verificacion',
   'Gijón: espacio deportivo de 22.000 m² con 10 pistas de pádel.'),
  ('Real Grupo de Cultura Covadonga', 'real-grupo-cultura-covadonga', 'Gijón', 'Asturias',
   'Camino de la Guía, 17, 33212 Gijón', 43.5391, -5.6762, true,
   '+34 985 31 00 00', '', '',
   '6 pistas indoor', true, 'sintético', 'Socios / Teléfono', true, false,
   false, 'pendiente_verificacion',
   'Gijón: histórico club social con 6 pistas de pádel cubiertas.'),
  ('Padel P3', 'padel-p3', 'Gijón', 'Asturias',
   'Calle Río Piles, s/n, 33203 Gijón', 43.5388, -5.6449, true,
   '+34 985 00 00 00', '', '',
   '4 pistas indoor', true, 'sintético', 'Playtomic', false, false,
   false, 'pendiente_verificacion',
   'Gijón: 4 pistas de pádel cubiertas.'),
  -- L'Hospitalet de Llobregat
  ('Padel Indoor Hospitalet', 'padel-indoor-hospitalet', 'L''Hospitalet de Llobregat', 'Barcelona',
   'Av. del Carrilet, 225, 08907 L''Hospitalet de Llobregat', 41.3597, 2.0994, true,
   '+34 930 00 00 00', 'info@padelindoorhospitalet.com', 'https://padelindoorhospitalet.com/',
   '24 pistas indoor', true, 'sintético', 'Web Propia / Playtomic', true, true,
   false, 'pendiente_verificacion',
   'L''Hospitalet de Llobregat: 24 pistas de pádel indoor.'),
  -- A Coruña (y área metropolitana)
  ('A1 Pádel Club', 'a1-padel-club', 'A Coruña', 'A Coruña',
   'C/ Galileo Galilei, 36, 15008 A Coruña', 43.3623, -8.4115, true,
   '+34 658 92 34 23', 'recepcion@a1-padel.com', 'https://www.a1-padel.com/',
   'Pistas indoor', true, 'sintético', 'Web Propia', true, false,
   false, 'pendiente_verificacion',
   'A Coruña: club de pádel indoor con zona fit y ligas.'),
  ('AC Padel Coruña', 'ac-padel-coruna', 'Cambre', 'A Coruña',
   'Rua Polígono El Temple, 21, 15679 Cambre', 43.2936, -8.346, true,
   '+34 981 00 00 00', '', '',
   '6 pistas indoor de cristal', true, 'sintético', 'Playtomic', true, true,
   false, 'pendiente_verificacion',
   'Cambre (A Coruña): 6 pistas indoor de cristal con escuela y tienda.'),
  ('Pádel M9', 'padel-m9', 'Culleredo', 'A Coruña',
   'Calle Liñares, 45, 15189 Culleredo', 43.2877, -8.3889, true,
   '+34 981 00 00 00', '', '',
   '6 pistas indoor', true, 'sintético', 'Playtomic', true, false,
   false, 'pendiente_verificacion',
   'Culleredo (A Coruña): 6 pistas de pádel indoor.'),
  ('Padel D3', 'padel-d3', 'Bergondo', 'A Coruña',
   'Rúa Parroquia de Rois, 1H, 15165 Bergondo', 43.3244, -8.2486, true,
   '+34 981 00 00 00', '', '',
   '4 pistas de cristal', true, 'sintético', 'Playtomic', true, false,
   false, 'pendiente_verificacion',
   'Bergondo (A Coruña): 4 pistas de cristal a 10 minutos de La Coruña.'),
  -- Vitoria-Gasteiz
  ('Bakh', 'bakh', 'Vitoria-Gasteiz', 'Álava',
   'Avenida del Zadorra, 100, 01015 Vitoria-Gasteiz', 42.8467, -2.6716, true,
   '+34 945 00 00 00', 'info@bakh.es', 'https://www.bakh.es/',
   '10 pistas (8 cubiertas, 2 descubiertas)', true, 'sintético', 'Web Propia', true, false,
   false, 'pendiente_verificacion',
   'Vitoria-Gasteiz: mayor centro de pádel de Álava con 10 pistas.'),
  ('Padel Pista Norte Vitoria', 'padel-pista-norte-vitoria', 'Vitoria-Gasteiz', 'Álava',
   'Polígono Industrial de Jundiz, 01015 Vitoria-Gasteiz', 42.8487, -2.6971, true,
   '+34 945 00 00 00', '', 'https://padelpistanorte.com/',
   'Pistas indoor', true, 'sintético', 'Web Propia', true, true,
   false, 'pendiente_verificacion',
   'Vitoria-Gasteiz: centro con tienda, tecnificación y ligas.'),
  ('Peña Vitoriana Tenis Club', 'pena-vitoriana-tenis-club', 'Vitoria-Gasteiz', 'Álava',
   'Calle Arriagabaster, s/n, 01007 Vitoria-Gasteiz', 42.8559, -2.6771, true,
   '+34 945 00 00 00', '', 'https://www.pvitoriana.com/',
   '4 pistas cubiertas (2 cristal, 2 muro)', true, 'sintético / muro', 'Web Propia / Teléfono', true, false,
   false, 'pendiente_verificacion',
   'Vitoria-Gasteiz: 4 pistas cubiertas (cristal y muro) con escuela.'),
  ('Fundación Estadio Vital', 'fundacion-estadio-vital', 'Vitoria-Gasteiz', 'Álava',
   'Paseo de Cervantes, 23, 01007 Vitoria-Gasteiz', 42.8575, -2.6726, true,
   '+34 945 00 00 00', '', 'https://www.fundacionestadio.eus/',
   '4 pistas (2 cubiertas, 2 descubiertas)', true, 'césped artificial', 'Web Propia', true, false,
   false, 'pendiente_verificacion',
   'Vitoria-Gasteiz: pistas municipales de la Fundación Estadio Vital.'),
  -- Elche
  ('360 Padel Elche', '360-padel-elche', 'Elche', 'Alicante',
   'Carretera Murcia-Alicante, km 51 (Nave Lamitex), 03205 Elche', 38.2656, -0.6984, true,
   '+34 966 00 00 00', 'info@360padel.es', 'https://360padel.es/',
   '9 pistas indoor + 3 outdoor', true, 'sintético', 'Web Propia', true, false,
   false, 'pendiente_verificacion',
   'Elche: 9 pistas indoor y 3 outdoor con cafetería.'),
  ('Ipadel Elche', 'ipadel-elche', 'Elche', 'Alicante',
   'Calle Algorfa, 10, 03207 Elche', 38.2671, -0.6912, true,
   '+34 693 63 43 92', 'ipadelelche@gmail.com', '',
   'Pistas indoor', true, 'sintético', 'Playtomic', true, false,
   false, 'pendiente_verificacion',
   'Elche: centro de pádel indoor.'),
  ('Vola Indoor Carrús', 'vola-indoor-carrus', 'Elche', 'Alicante',
   'Calle Petrer, 5, 03206 Elche', 38.2645, -0.7048, true,
   '+34 693 63 43 92', 'infopadelelche@gmail.com', '',
   'Pistas indoor', true, 'sintético', 'Playtomic', true, false,
   false, 'pendiente_verificacion',
   'Elche: club indoor en el barrio de Carrús.'),
  -- Granada (y área metropolitana)
  ('Campus Pádel Club Granada', 'campus-padel-club-granada', 'Granada', 'Granada',
   'Campus Universitario de Cartuja, s/n, 18071 Granada', 37.1773, -3.5986, true,
   '+34 958 00 00 00', '', '',
   'Pistas indoor', true, 'sintético', 'Playtomic', true, false,
   false, 'pendiente_verificacion',
   'Granada: club de pádel con escuela y ligas.'),
  ('Box Pádel Granada', 'box-padel-granada', 'Churriana de la Vega', 'Granada',
   'Camino Puente del Palo, s/n, 18194 Churriana de la Vega', 37.144, -3.6438, true,
   '+34 958 00 00 00', '', '',
   '4 pistas indoor', true, 'sintético', 'Playtomic', true, false,
   false, 'pendiente_verificacion',
   'Churriana de la Vega (Granada): 4 pistas de pádel indoor.'),
  ('Padel Master Club', 'padel-master-club', 'Granada', 'Granada',
   'C. Periodista Luis de Vicente, 1, 18014 Granada', 37.1891, -3.6027, true,
   '+34 640 14 61 25', 'info@padelmaster.top', '',
   'Pistas indoor', true, 'sintético', 'Web Propia', true, true,
   false, 'pendiente_verificacion',
   'Granada: club de pádel con tienda, bar y torneos.'),
  ('Bola de Oro (PMD Granada)', 'bola-de-oro-pmd-granada', 'Granada', 'Granada',
   'C/ Santo Sepulcro, s/n (acceso Av. de Cervantes), 18008 Granada', 37.1667, -3.6005, true,
   '+34 958 00 00 00', '', '',
   '5 pistas de cristal', false, 'sintético', 'Web PMD Granada', true, false,
   false, 'pendiente_verificacion',
   'Granada: instalación municipal con 5 pistas de pádel de cristal.'),
  -- Terrassa
  ('FCV Pádel Indoor Terrassa', 'fcv-padel-indoor-terrassa', 'Terrassa', 'Barcelona',
   'Carretera de Rubí, 288, 08228 Terrassa', 41.561, 2.0083, true,
   '+34 937 00 00 00', 'info@fcvpadel.com', 'https://www.fcvpadel.com/',
   '7 pistas panorámicas indoor', true, 'panorámico', 'Web Propia / Playtomic', true, false,
   false, 'pendiente_verificacion',
   'Terrassa: 7 pistas panorámicas indoor con gimnasio y bar-restaurante.'),
  -- Badalona
  ('Pàdel Indoor Badalona', 'padel-indoor-badalona', 'Badalona', 'Barcelona',
   'Ctra. de Mataró, 7, 08911 Badalona', 41.447, 2.2472, true,
   '+34 933 00 00 00', 'info@padelindoorbadalona.com', 'https://padelindoorbadalona.com/',
   '7 pistas (1 panorámica)', true, 'sintético', 'Web Propia / Playtomic', true, false,
   false, 'pendiente_verificacion',
   'Badalona: 7 pistas de pádel indoor a 5 minutos de Barcelona.'),
  -- Sabadell
  ('Club Pàdel Sabadell', 'club-padel-sabadell', 'Sabadell', 'Barcelona',
   'Ctra. de Prats de Lluçanès, s/n, 08206 Sabadell', 41.543, 2.1094, true,
   '+34 937 00 00 00', '', 'https://enjoypadelsabadell.com/',
   '9 pistas de pádel', true, 'sintético', 'Web Propia / Playtomic', true, false,
   false, 'pendiente_verificacion',
   'Sabadell: 9 pistas de pádel con compromiso de comodidad todo el año.'),
  ('Indoor Padel Sabadell', 'indoor-padel-sabadell', 'Sabadell', 'Barcelona',
   'Polígono Sant Pau de Riu-sec, 08205 Sabadell', 41.5493, 2.1021, true,
   '+34 663 84 69 63', '', 'https://indoorpadelsabadell.com/',
   '10 pistas indoor', true, 'sintético', 'Web Propia', true, true,
   false, 'pendiente_verificacion',
   'Sabadell: 10 pistas indoor nuevas con tienda y cafetería.'),
  -- Oviedo
  ('Pádel Oviedo', 'padel-oviedo', 'Oviedo', 'Asturias',
   'Pérez Galdós, 6, 33012 Oviedo', 43.3619, -5.8494, true,
   '+34 690 98 46 62', '', '',
   '7 pistas indoor', true, 'sintético', 'Web Propia / Playtomic', true, false,
   false, 'pendiente_verificacion',
   'Oviedo: 7 pistas de pádel indoor.'),
  ('El Soho Padel Club', 'el-soho-padel-club', 'Oviedo', 'Asturias',
   'Calle Río Sella, 33010 Oviedo', 43.3558, -5.8421, true,
   '+34 985 00 00 00', '', '',
   '7 pistas indoor', true, 'sintético', 'Playtomic', true, false,
   false, 'pendiente_verificacion',
   'Oviedo: 7 pistas de pádel indoor.'),
  ('Centro Asturiano de Oviedo', 'centro-asturiano-de-oviedo', 'Oviedo', 'Asturias',
   'Calle Doctor Alfredo Martínez, 6, 33005 Oviedo', 43.3584, -5.8484, true,
   '+34 985 22 00 00', '', 'https://caoviedo.es/',
   '6 pistas cubiertas', true, 'sintético', 'Socios / Teléfono', true, false,
   false, 'pendiente_verificacion',
   'Oviedo: 6 pistas de pádel cubiertas del histórico club social.'),
  -- Cartagena
  ('Club de Pádel Cartagena', 'club-de-padel-cartagena', 'Cartagena', 'Murcia',
   'Carr. de Murcia, 4, 30319 Cartagena', 37.6053, -0.9914, true,
   '+34 608 02 74 82', '', '',
   '11 pistas indoor', true, 'sintético', 'Playtomic / Teléfono', true, false,
   false, 'pendiente_verificacion',
   'Cartagena: 11 pistas de pádel cubiertas de última generación.'),
  ('Padel Center Cartago', 'padel-center-cartago', 'Cartagena', 'Murcia',
   'Polígono Industrial Cabezo Beaza, 30353 Cartagena', 37.6351, -0.9568, true,
   '+34 968 00 00 00', '', '',
   '8 pistas cubiertas + 1 exterior', true, 'sintético', 'Playtomic', true, false,
   false, 'pendiente_verificacion',
   'Cartagena: 8 pistas cubiertas y 1 exterior en Cabezo Beaza.'),
  ('Club Deportivo Santa Ana', 'club-deportivo-santa-ana-cartagena', 'Cartagena', 'Murcia',
   'C. Padua, 2, Residencial Santa Ana, 30319 Cartagena', 37.6211, -0.9644, true,
   '+34 968 00 00 00', '', '',
   '7 pistas outdoor', false, 'sintético / cristal', 'Teléfono', true, false,
   false, 'pendiente_verificacion',
   'Cartagena: 7 pistas de pádel al aire libre en Residencial Santa Ana.'),
  ('Ilusion Sport Center', 'ilusion-sport-center', 'Cartagena', 'Murcia',
   'Calle Dr. Pérez Espejo, s/n, 30203 Cartagena', 37.5996, -0.9827, true,
   '+34 968 00 00 00', '', '',
   '3 pistas de pádel', true, 'sintético', 'Playtomic', true, false,
   false, 'pendiente_verificacion',
   'Cartagena: 3 pistas de pádel en el centro deportivo.')
on conflict (slug) do nothing;